[package]
name = "eph"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
which = "4.3"
dirs = "4.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
